### PR TITLE
Multiple fixes on Android

### LINKED ISSUE #625: CallUUID changes after `startCall`
# Bug report

- [ ] I've checked the [example](https://github.com/react-native-webrtc/react-native-callkeep/tree/master/example) to reproduce the issue.

- Reproduced on:
 - [x] Android
 - [ ] iOS

## Description

On android the `callUuid` set with `startCall` is not kept afterward.

## Steps to Reproduce

With a snippet like this:

```javascript
const callUuid = 'ccb3991f-9606-40d7-ba98-a021a0ecb4a0';

RNCallKeep.addEventListener('didReceiveStartCallAction', ({ callUUID }) => {
  console.log('didReceiveStartCallAction', callUUID, callUuid)
})
RNCallKeep.startCall(callUuid, '+15555555555', 'John Doe', 'generic', false)
```

You can easily notice something like the following in the logs:

```log
didReceiveStartCallAction 1444793b-ec42-4cf0-a1f2-7ab9693a9793 ccb3991f-9606-40d7-ba98-a021a0ecb4a0
```

## Versions
    - Callkeep: 8fef467243adc52dc85e732f806472f3a8ebd4a8
    - React Native: 0.65.1
    - iOS: ~
    - Android: ~
    - Phone model: ~

## Logs

```
11-08 11:29:15.273 18234 20342 D RNCallKeep: [RNCallKeepModule] startCall called, uuid: ccb3991f-9606-40d7-ba98-a021a0ecb4a0, number: +15555555555, callerName: John Doe
11-08 11:29:15.275 18234 20342 D RNCallKeep: [RNCallKeepModule] startCall, uuid: ccb3991f-9606-40d7-ba98-a021a0ecb4a0
11-08 11:29:15.597 18234 18234 D RNCallKeep: [VoiceConnectionService] Constructor
11-08 11:29:15.636 18234 18234 D RNCallKeep: [VoiceConnectionService] onCreateOutgoingConnection, uuid:1444793b-ec42-4cf0-a1f2-7ab9693a9793
11-08 11:29:15.637 18234 18234 D RNCallKeep: [VoiceConnectionService] makeOutgoingCall, uuid:1444793b-ec42-4cf0-a1f2-7ab9693a9793, number: +15555555555, displayName:John Doe
11-08 11:29:15.637 18234 18234 D RNCallKeep: [VoiceConnectionService] onCreateOutgoingConnection: disabling multi calls
11-08 11:29:15.637 18234 18234 D RNCallKeep: [VoiceConnectionService] createConnection, callerNumber:tel:%2B15555555555
11-08 11:29:15.638 18234 18234 D RNCallKeep: [VoiceConnectionService] PhoneAccount is not SELF_MANAGED, so connection won't be either
11-08 11:29:15.638 18234 18234 D RNCallKeep: [VoiceConnection] onStateChanged called, state : 0
11-08 11:29:15.638 18234 18234 D RNCallKeep: [VoiceConnection] onStateChanged called, state : 3
11-08 11:29:15.638 18234 18234 D RNCallKeep: [VoiceConnectionService] startForegroundService
11-08 11:29:15.640 18234 18234 D RNCallKeep: [VoiceConnectionService] Starting foreground service
11-08 11:29:15.643 18234 18234 D RNCallKeep: [VoiceConnectionService] onCreateOutgoingConnection: initializing connection on Samsung device
11-08 11:29:15.643 18234 18234 D RNCallKeep: [VoiceConnection] onStateChanged called, state : 1
11-08 11:29:15.643 18234 18234 D RNCallKeep: [VoiceConnectionService] sendCallRequestToActivity, action:ACTION_ONGOING_CALL
11-08 11:29:15.643 18234 18234 D RNCallKeep: [VoiceConnectionService] sendCallRequestToActivity, action:ACTION_AUDIO_SESSION
11-08 11:29:15.643 18234 18234 D RNCallKeep: [VoiceConnectionService] onCreateOutgoingConnection: done
11-08 11:29:15.646 18234 18234 D RNCallKeep: [RNCallKeepModule][onReceive] :ACTION_ONGOING_CALL
11-08 11:29:15.646 18234 18234 V RNCallKeep: [RNCallKeepModule] sendEventToJS, eventName: RNCallKeepDidReceiveStartCallAction, bound: true, hasListeners: true args : { NativeMap: {"name":"John Doe","callUUID":"1444793b-ec42-4cf0-a1f2-7ab9693a9793","handle":"+15555555555"} }
11-08 11:29:15.655 18234 18234 D RNCallKeep: [RNCallKeepModule][onReceive] :ACTION_AUDIO_SESSION
11-08 11:29:15.655 18234 18234 V RNCallKeep: [RNCallKeepModule] sendEventToJS, eventName: RNCallKeepDidActivateAudioSession, bound: true, hasListeners: true args : null
11-08 11:29:15.729 18234 18234 D RNCallKeep: [VoiceConnection] onCallAudioStateChanged muted :false
11-08 11:29:15.729 18234 18234 D RNCallKeep: [RNCallKeepModule][onReceive] :ACTION_DID_CHANGE_AUDIO_ROUTE
11-08 11:29:15.729 18234 18234 V RNCallKeep: [RNCallKeepModule] sendEventToJS, eventName: RNCallKeepDidChangeAudioRoute, bound: true, hasListeners: true args : { NativeMap: {"output":"SPEAKER","callUUID":"1444793b-ec42-4cf0-a1f2-7ab9693a9793","handle":"%2B15555555555"} }
11-08 11:29:15.739 18234 18234 D RNCallKeep: [VoiceConnection] onCallAudioStateChanged muted :false
11-08 11:29:15.740 18234 18234 D RNCallKeep: [VoiceConnection] onCallAudioStateChanged muted :false
11-08 11:29:15.740 18234 18234 D RNCallKeep: [RNCallKeepModule][onReceive] :ACTION_DID_CHANGE_AUDIO_ROUTE
11-08 11:29:15.742 18234 18234 V RNCallKeep: [RNCallKeepModule] sendEventToJS, eventName: RNCallKeepDidChangeAudioRoute, bound: true, hasListeners: true args : { NativeMap: {"output":"SPEAKER","callUUID":"1444793b-ec42-4cf0-a1f2-7ab9693a9793","handle":"%2B15555555555"} }
11-08 11:29:15.743 18234 18234 D RNCallKeep: [VoiceConnection] onCallAudioStateChanged muted :false
11-08 11:29:15.743 18234 18234 D RNCallKeep: [RNCallKeepModule][onReceive] :ACTION_DID_CHANGE_AUDIO_ROUTE
11-08 11:29:15.743 18234 18234 V RNCallKeep: [RNCallKeepModule] sendEventToJS, eventName: RNCallKeepDidChangeAudioRoute, bound: true, hasListeners: true args : { NativeMap: {"output":"SPEAKER","callUUID":"1444793b-ec42-4cf0-a1f2-7ab9693a9793","handle":"%2B15555555555"} }
11-08 11:29:15.743 18234 18234 D RNCallKeep: [RNCallKeepModule][onReceive] :ACTION_DID_CHANGE_AUDIO_ROUTE
11-08 11:29:15.744 18234 18234 V RNCallKeep: [RNCallKeepModule] sendEventToJS, eventName: RNCallKeepDidChangeAudioRoute, bound: true, hasListeners: true args : { NativeMap: {"output":"SPEAKER","callUUID":"1444793b-ec42-4cf0-a1f2-7ab9693a9793","handle":"%2B15555555555"} }
11-08 11:29:22.151 18234 18234 D RNCallKeep: [VoiceConnection] onStateChanged called, state : 6
11-08 11:29:22.151 18234 18234 D RNCallKeep: [VoiceConnection] onDisconnect executed
11-08 11:29:22.151 18234 18234 D RNCallKeep: [VoiceConnectionService] deinitConnection:1444793b-ec42-4cf0-a1f2-7ab9693a9793
11-08 11:29:22.151 18234 18234 D RNCallKeep: [VoiceConnectionService] stopForegroundService
11-08 11:29:22.166 18234 18234 D RNCallKeep: [RNCallKeepModule][onReceive] :ACTION_END_CALL
11-08 11:29:22.166 18234 18234 V RNCallKeep: [RNCallKeepModule] sendEventToJS, eventName: RNCallKeepPerformEndCallAction, bound: true, hasListeners: true args : { NativeMap: {"callUUID":"1444793b-ec42-4cf0-a1f2-7ab9693a9793"} }
```

## Diagnostic

I did a small dig in the project and I guess the issue comes from this line:

https://github.com/react-native-webrtc/react-native-callkeep/blob/4b1fa98a685f6502d151875138b7c81baf1ec680/android/src/main/java/io/wazo/callkeep/VoiceConnectionService.java#L218

### PR DESCRIPTION
**Pull request by saif-o99**
This PR deliver some fixes & new code 

1- `checkIsInManagedCall` was added to check if there is a native active call in android, in my case this was useful to check if there is a native active call, prevent app from making a call

2- `onHasActiveCall` was added to tell the JS side about native call status, in my case this covered the case where you are in an app call then you accept a native call, this will trigger this event which i end the call by it. so no two calls be on the same time. before, the two calls were running at the same time

3- change in VoiceConnectionService.java is to fix #625

4- `onHostDestroy` has been added to stop all calls and processes when app is killed

### CODE REVIEW

**Comment by saif-o99** [comment]
@manuquentin Can you please check this? Thanks

File: android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java [hunk 1]
```diff
@@ -217,6 +224,125 @@ public void initializeTelecomManager() {
...
+    }
+
+    private class CallStateListener extends TelephonyCallback implements TelephonyCallback.CallStateListener {
+
+          @Override
+          public void onCallStateChanged(int state) {
+              switch (state) {
+                  case TelephonyManager.CALL_STATE_RINGING:
+                      // Incoming call is ringing (not used for outgoing call).
+                      Log.i("onCallStateChanged", "CALL_STATE_RINGING");
```
Comment (manuquentin) [inline android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java:276]: Are those debug logs useful ? Eg, all `Log.i()` doesn't seem to provide meaningful information

File: android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java [hunk 2]
```diff
@@ -217,6 +224,125 @@ public void initializeTelecomManager() {
...
+        }else if(Build.VERSION.SDK_INT < Build.VERSION_CODES.S && legacyCallStateListener != null){
+            telephonyManager.listen(legacyCallStateListener, PhoneStateListener.LISTEN_NONE);
+        }
+    }
+
+    public void listenToNativeCallsState() {
+        Context context = this.getAppContext();
+        int permissionCheck = ContextCompat.checkSelfPermission(context, Manifest.permission.READ_PHONE_STATE);
+        if (permissionCheck == PackageManager.PERMISSION_GRANTED) {
+        Log.d(TAG, "[RNCallKeepModule] listenToNativeCallsState");
```
Comment (manuquentin) [inline android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java:320]: Indentation issues

File: android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java [hunk 3]
```diff
@@ -217,6 +224,125 @@ public void initializeTelecomManager() {
...
+        Context context = this.getAppContext();
+        int permissionCheck = ContextCompat.checkSelfPermission(context, Manifest.permission.READ_PHONE_STATE);
+        if (permissionCheck == PackageManager.PERMISSION_GRANTED) {
+                return telecomManager.isInManagedCall();
+        }
+         return false;
+    }
+
+    @ReactMethod
+        public void checkIsInManagedCall(Promise promise) {
```
Comment (manuquentin) [inline android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java:341]: Indentation issue

File: android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java [hunk 4]
```diff
@@ -597,6 +725,37 @@ public void reportEndCallWithUUID(String uuid, int reason) {
...
 
+   @Override
+   public void onHostResume() {
+       Log.d(TAG, "onResume()");
+   }
+
+   @Override
+   public void onHostPause() {
+       Log.d(TAG, "onPause()");
+   }
```
Comment (manuquentin) [inline android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java:736]: Can we remove this ?

File: android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java [hunk 5]
```diff
@@ -597,6 +725,37 @@ public void reportEndCallWithUUID(String uuid, int reason) {
...
+
+   @Override
+   public void onHostDestroy() {
+      // when activity destroyed end all calls
+       Log.d(TAG, "onDestroy()");
```
Comment (manuquentin) [inline android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java:741]: `onHostDestroy`

**Review by manuquentin — CHANGES_REQUESTED** [review]

File: android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java (hunk 1 above)
Comment (saif-o99) [reply android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java:276]: Not a big deal, they just tell us where we are. want me to remove them ?

File: android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java (hunk 4 above)
Comment (saif-o99) [reply android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java:736]: Unforitunely no, if i removed them the build will failed, if you overrided one of them you to override the three of them

File: android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java (hunk 5 above)
Comment (saif-o99) [reply android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java:741]: Whats wrong here?

File: android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java (hunk 1 above)
Comment (saif-o99) [reply android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java:276]: @manuquentin

File: android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java (hunk 5 above)
Comment (manuquentin) [reply android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java:741]: The log should be : `Log.d(TAG, "onHostDestroy()");` not `Log.d(TAG, "onDestroy()");`

File: android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java (hunk 4 above)
Comment (manuquentin) [reply android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java:736]: Ok so could you remove the log please ?

File: android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java (hunk 1 above)
Comment (manuquentin) [reply android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java:276]: Yes because when you make a `adb logcat` you don't want to be flooded by un-meaningful logs

**Comment by saif-o99** [comment]
@manuquentin Done

File: README.md [hunk 6]
```diff
@@ -993,6 +1005,19 @@ RNCallKeep.addEventListener('checkReachability', () => {
 
 ```
 
+### onHasActiveCall
+
+_Android only._
+
+A listener to tells the JS side if a native call has been answered while there is active self managed call
```
Comment (wilmxre) [inline README.md:1012]: "A listener that tells the JS side if a native call has been answered while there was an active self managed call" could be a more correct description imo

**Review by wilmxre — APPROVED** [review]

**Comment by saif-o99** [comment]
hey @manuquentin , is this gonna be merged soon?

**Review by manuquentin — APPROVED** [review]

**Comment by dkornilove** [comment]
@saif-o99, @manuquentin, the new `onHostDestroy` behavior should be optional. I spent two days debugging after updating my app dependencies because the foreground service and current call started to disappear when the app is swiped away from recents. So this was unexpected breaking feature for me

**Comment by dkornilove** [comment]
@saif-o99 Speaking for myself, this behavior is unexpected and likely affects others as well. Throughout the library's existence, the behavior has been consistent, and its sudden change without announcement is surprising. I utilize foreground services not only for calls, so it's critical for me that the activity isn't completely killed after closing the app. The foreground service is designed to continue functioning even when the app is closed. Why does a library responsible only for calls override the behavior of the entire application?
