### PR TITLE
Minor updates

### LINKED ISSUE #95: [Android] displayIncomingCall either doesn't called or called with a long delay in when the app is launched from high priority FCM arrives and device in idle mode (Doze)
I'm trying to solve the following problem: receiving an incoming call and displaying an incoming call window in the application, even when the application is killed.

I assume this is solved as follows:
1) High priority FCM message is sent to the Android 10 device (Pixel 2).
2) The App start the HeadlessJS task and call the RNCallKeep.displayIncomingCall function.

My FCM messages looks like this:

```json
{
   "data":
		{
			"message":"New call",
			"sound":"default",
			"title":"New INVITE",
			"to":"123@test.net",
			"type":2
		},
    "priority":"high",
    "registration_ids": ["xxx"],
 } 
```

Implementation of FCM messages processing and display of an incoming call:
```JS
index.js

...
AppRegistry.registerHeadlessTask('RNFirebaseBackgroundMessage', () => bgMessaging);
...
```
```JS
bgMessaging.js

...
export default async (message: RemoteMessage) => {
   const options = {
        ios: {
            appName: 'MyApp',
            imageName: '../img/TabBar/contacts.imageset/contacts.png',
            ringtoneSound: 'my_ringtone_sound_filename_in_bundle',
            maximumCallGroups: '1',
            maximumCallsPerCallGroup: '1'
        },
        android: {
            alertTitle: 'Permissions Required',
            alertDescription: 'This application needs to access your phone calling accounts to make calls',
            cancelButton: 'Cancel',
            okButton: 'ok',
            imageName: 'sim_icon',
            additionalPermissions: [PermissionsAndroid.PERMISSIONS.READ_CONTACTS]
        }
    };

    RNCallKeep.setup(options);
    RNCallKeep.setAvailable(true);
   
    if(message.data.type==='2'){
            let _uuid = uuid.v4();
            RNCallKeep.displayIncomingCall(_uuid, "123", "123");
    }

    return Promise.resolve();
}
```

This works fine and the incoming call screen is displayed:
1) If the App has just been killed and the device display is still active.
2) If the App has just been killed and the device’s display has been blocked for a while.

This **doesn't work** or works with a **long delay** (about 60 sec after FCM received I see incoming call display) if the App was killed and the device’s screen was blocked and some time passed, for example 5 minutes. I think device in idle mode (Doze) in this moment . 

What's wrong? How to make guaranteed to open the window of an incoming call after the arrival of a high-priority FCM-message in idle-mode (and inactive-mode) device?

### PR DESCRIPTION
**Pull request by manuquentin**
- Fixes #95 
- Deprecate `reportUpdatedCall` which do the same job as `updateDisplay`.
- Update example to allow call to `updateDisplay`

### CODE REVIEW

File: example/App.js [hunk 1]
```diff
@@ -182,6 +184,18 @@ export default function App() {
     setCallMuted(callUUID, muted);
   };
 
+  const updateDisplay = (callUUID) => {
+    const number = calls[callUUID];
+    // Workaround because Android doesn't display well displayName, se we have to switch ...
+    if (isIOS) {
```
Comment (manuquentin) [inline example/App.js]: @kylekurz @bhuangy @danjenkins on Android I have to switch `displayName` and `handle` arguments to have them displayed correctly (unless the `displayName` is not taken in account). 
Weirdly the Android code [seems to be OK](https://github.com/react-native-webrtc/react-native-callkeep/blob/master/android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java#L339-L340) ...

Have you this issue too ? I can reproduce with the example on a Pixel 1 (Android 9).

Comment (danjenkins) [reply example/App.js]: I don't use the updateDisplay api yet so I can't comment :)

Comment (kylekurz) [reply example/App.js]: I'd rather update the underlying modules so they can both have the arguments in the same order, instead of doing a platform check here, personally...

Comment (manuquentin) [reply example/App.js]: Me too but my point is that the arguments on the Android side [are good](https://github.com/react-native-webrtc/react-native-callkeep/blob/master/android/src/main/java/io/wazo/callkeep/RNCallKeepModule.java#L339-L340). I don't want to call `setAddress` with the displayName and `setCallerDisplayName` with the handle ...

Comment (kylekurz) [reply example/App.js]: This doesn't really make sense. We should be figuring out what's going on underneath instead of providing a strange example.

For our app, we have the following scenarios:

1. Incoming call - Always displays name properly
2. Outgoing call started from our app - Always displays name properly
3. Outgoing call started from native dialer - Only displays the number

Does this match your experience? I think if you switch the items, you'll end up with a call log that has the right name, but the URI will be useless if someone tries to call it back.
